# Generated by Django 4.2 on 2023-04-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Укажите ключ', max_length=50, verbose_name='Ключ')),
                ('value', models.CharField(help_text='Укажите значение', max_length=50, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Укажите значение', verbose_name='Значение')),
                ('modified_by', models.ForeignKey(help_text='Укажите редактора', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('properties', models.ManyToManyField(help_text='Укажите свойства', related_name='properties', to='core.property')),
            ],
        ),
    ]
